CREATE TABLE IF NOT EXISTS follow_notifications (
    id INTEGER PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read INTEGER DEFAULT 0,
    FOREIGN KEY (id) REFERENCES follows (id) ON DELETE CASCADE
);
