CREATE TABLE IF NOT EXISTS like_notifications (
    id INTEGER PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL,
    read INTEGER DEFAULT 0,
    FOREIGN KEY (id) REFERENCES likes (id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);